SELECT A.Loan_Nbr,[TAG_2_VAL],C.EXCP_ID,A.[MCA_PERCENT],A.[LOAN_STATUS],B.[HUD_STS_DESC],F.[FNL_RVW_STS_DESC],POR_INCUR_CLEAR
INTO #BASE1
from Reverse_Dw.[dbo].[RM_CHAMPION_MASTER_TBL_CURR_VW] A
LEFT JOIN (SELECT * FROM REVERSE_DW.[dbo].[HUD_ASGN_HUD_STS] WHERE CURR_IND = 'Y') B
	ON A.loan_nbr = b.Loan_Nbr
LEFT JOIN (SELECT EXCP.LOAN_NBR,EXCP.EXCP_ID FROM REVERSE_DW.[dbo].[HUD_ASGN_EXCP_EDW] EXCP  WHERE CURR_IND = 'Y' AND (DOC_DESC <> 'Proof of Repair' AND [EXCP_STS_DESC] = 'Resolved by ML') OR (DOC_DESC = 'Proof of Repair' AND [EXCP_STS_DESC] IN ('Resolved','Resolved by ML'))) C
	ON C.LOAN_NBR = A.LOAN_NBR
LEFT JOIN (SELECT POR1.EXCP_ID,MIN(EFF_DTTM) AS 'POR_INCUR_CLEAR' FROM REVERSE_DW.[dbo].[HUD_ASGN_EXCP_EDW] POR1
			RIGHT JOIN (SELECT EXCP_ID,MAX(EFF_DTTM) AS 'POR_INCUR' FROM REVERSE_DW.[dbo].[HUD_ASGN_EXCP_EDW] WHERE DOC_DESC = 'Proof of Repair' AND [EXCP_STS_DESC] = 'Incurable' GROUP BY EXCP_ID) POR2
						ON POR1.EXCP_ID = POR2.EXCP_ID
						WHERE DOC_DESC = 'Proof of Repair' AND [EXCP_STS_DESC] <> 'Incurable' AND POR1.EFF_DTTM >= POR_INCUR GROUP BY POR1.EXCP_ID) E
	ON C.EXCP_ID = E.EXCP_ID
LEFT JOIN (SELECT Loan_Nbr,[FNL_RVW_STS_DESC] FROM REVERSE_DW.[dbo].[HUD_ASGN_FNL_RVW]WHERE CURR_IND = 'Y') F
	ON A.LOAN_NBR = F.LOAN_NBR
RIGHT JOIN (SELECT LOAN_NBR,[GRP_DESC],[TAG_2_VAL] FROM REVERSE_DW.[dbo].[HUD_ASGN_LOANS] WHERE CURR_IND = 'Y' AND ISNULL([GRP_DESC],'No Group') <> 'Grp 5 BofA GNMAs') D
	 ON CAST(A.Loan_Nbr AS VARCHAR) = CAST(D.Loan_Nbr AS VARCHAR)
--WHERE [LOAN_STATUS] = 'Liquidated/Assigned to HU' OR B.[HUD_STS_DESC] IN ('Pkg Submitted to HUD','HUD Approved')


SELECT A.Loan_Nbr,[TAG_2_VAL],A.[MCA_PERCENT],A.[LOAN_STATUS],A.[HUD_STS_DESC],A.[FNL_RVW_STS_DESC],AA.EXCP_ID,AA.DOC_DESC,AA.ISSU_DESC,EXCP_CLOSED,POR_INCUR_CLEAR
INTO #BASE2 
FROM #BASE1 A
LEFT JOIN REVERSE_DW.[dbo].[HUD_ASGN_EXCP_EDW] AA 
	ON AA.EXCP_ID = A.EXCP_ID
LEFT JOIN (SELECT [EXCP_ID],MIN([EFF_DTTM]) AS 'EXCP_CLOSED' FROM REVERSE_DW.[dbo].[HUD_ASGN_EXCP_EDW] WHERE [EXCP_STS_DESC] IN ('Resolved','Resolved by ML') AND CAST(EFF_DTTM AS DATE) >= CAST('3/27/2020' AS DATE) GROUP BY EXCP_ID) BB
	ON AA.EXCP_ID = BB.EXCP_ID 
WHERE AA.EFF_DTTM = BB.EXCP_CLOSED AND (([DOC_DESC] = 'Proof of Repair' AND EXCP_CLOSED >= CAST('3/27/2020' AS DATE) AND POR_INCUR_CLEAR >= CAST('3/27/2020' AS DATE)) OR 
										  [EXCP_STS_DESC] = 'Resolved by ML')


SELECT A.EXCP_ID,A.[EXCP_MM_DESC],A.[EFF_DTTM] AS 'MEMO_DATE',ROW_NUMBER() OVER(PARTITION BY A.[EXCP_ID] ORDER BY [EFF_DTTM] DESC) AS 'MEMO_ROW'
INTO #BASE3
FROM #BASE2 C
LEFT JOIN [dbo].[HUD_ASSGN_EXCP_ACTN_EDW] A
	ON C.EXCP_ID = A.EXCP_ID
LEFT JOIN (SELECT DISTINCT EXCP_ID,[EXCP_MM_DESC] from [dbo].[HUD_ASSGN_EXCP_ACTN_EDW]) B
	ON A.EXCP_ID = B.EXCP_ID 
WHERE A.EXCP_MM_DESC = B.EXCP_MM_DESC


SELECT DISTINCT A.*,MEMO_DATE_1,MEMO_1,MEMO_DATE_2,MEMO_2,MEMO_DATE_3,MEMO_3
FROM #BASE2 A
LEFT JOIN (SELECT EXCP_ID,MEMO_DATE AS 'MEMO_DATE_1',EXCP_MM_DESC AS 'MEMO_1' FROM #BASE3 WHERE MEMO_ROW = 1) B
	ON A.EXCP_ID = B.EXCP_ID 
LEFT JOIN (SELECT EXCP_ID,MEMO_DATE AS 'MEMO_DATE_2',EXCP_MM_DESC AS 'MEMO_2' FROM #BASE3 WHERE MEMO_ROW = 2) C
	ON A.EXCP_ID = C.EXCP_ID
LEFT JOIN (SELECT EXCP_ID,MEMO_DATE AS 'MEMO_DATE_3',EXCP_MM_DESC AS 'MEMO_3' FROM #BASE3 WHERE MEMO_ROW = 3) D
	ON A.EXCP_ID = D.EXCP_ID
ORDER BY DOC_DESC	


DROP TABLE #BASE1,#BASE2,#BASE3

 