DECLARE @MIN DATE
DECLARE	@MAX DATE
DECLARE @DT_INT INT

SET @MIN = '2020-04-01'
SET @MAX = '2020-04-30'
SET @DT_INT = 20200430

SELECT A.LOAN_NBR,@MIN AS 'Roll Month'
,CASE WHEN Roll_Pop = 'RI' THEN 'Roll In'
	  WHEN Roll_Pop = 'VI' THEN 'Vintage'
	  WHEN Roll_Pop = 'SM' THEN 'Slow Mover'
END AS 'Roll Pop'
,STATUS_CODE,STATUS_DESCRIPTION,B.DT_SBMT_TO_HUD AS 'Min Submitted',D.DT_SBMT_TO_HUD AS 'Max Submitted',
CASE
	WHEN STATUS_CODE = 72 THEN 'Resolved'
	WHEN STATUS_CODE = 0  AND D.DT_SBMT_TO_HUD IS NOT NULL THEN 'Resolved'
	WHEN STATUS_CODE <> 0 THEN 'Resolved'
	ELSE 'Pending'
END AS 'Final Status'
INTO #BASE
FROM Tact_Rev.[dbo].[HACGRollPop] ADHOC
INNER JOIN TACT_REV.DBO.HACGBonusBase A
	ON A.Loan_Nbr = ADHOC.loan_nbr
LEFT JOIN (SELECT ADHOC.Loan_nbr,min([DT_SBMT_TO_HUD]) AS 'DT_SBMT_TO_HUD' FROM Tact_Rev.[dbo].[HACGRollPop] ADHOC INNER JOIN [VRSQLRODS\RODS_PROD].Reverse_DW.Dbo.HUD_ASSGN_DT_SBMT_RESBMT A ON A.Loan_Nbr = ADHOC.loan_nbr
			WHERE CAST([DT_SBMT_TO_HUD] AS DATE) BETWEEN CAST(@MIN AS DATE) 
			AND CAST(@MAX AS DATE) GROUP BY ADHOC.LOAN_NBR) B
		ON A.LOAN_NBR = B.LOAN_NBR
/*LEFT JOIN (SELECT ADHOC.Loan_nbr,max([HUD_PRELIM_TTL_DNY_DT]) AS 'Denial_Dt' FROM Tact_Rev.[dbo].[HACGRollPop] ADHOC INNER JOIN [VRSQLRODS\RODS_PROD].Reverse_DW.[dbo].[HUD_ASGN_HUD_STS] A ON A.Loan_Nbr = ADHOC.loan_nbr WHERE [HUD_PRELIM_TTL_DNY_DT] IS NOT NULL AND CAST([HUD_PRELIM_TTL_DNY_DT] AS DATE)
			BETWEEN CAST(@MIN AS DATE) AND CAST(@MAX AS DATE) GROUP BY ADHOC.LOAN_NBR) C
		ON A.LOAN_NBR = C.LOAN_NBR*/
LEFT JOIN (SELECT ADHOC.Loan_nbr,MAX([DT_SBMT_TO_HUD]) AS 'DT_SBMT_TO_HUD' FROM Tact_Rev.[dbo].[HACGRollPop] ADHOC INNER JOIN [VRSQLRODS\RODS_PROD].Reverse_DW.Dbo.HUD_ASSGN_DT_SBMT_RESBMT A ON A.Loan_Nbr = ADHOC.loan_nbr
			WHERE CAST([DT_SBMT_TO_HUD] AS DATE) BETWEEN CAST(@MIN AS DATE) 
			AND CAST(@MAX AS DATE) GROUP BY ADHOC.LOAN_NBR) D
ON A.LOAN_NBR = D.LOAN_NBR

WHERE CAST(ADHOC.[DATE] AS DATE) = CAST(@MIN AS DATE) AND CAST(A.[DATE] AS DATE) = CAST(@MAX AS DATE)


ORDER BY [Final Status],[STATUS_CODE] DESC,D.DT_SBMT_TO_HUD DESC


