DECLARE @CURR_MONTH_END AS DATE = EOMONTH(GETDATE()) --EOMONTH('2020-05-01')
DECLARE @CURR_MONTH_INT AS INT = REPLACE(@CURR_MONTH_END,'-','')

DECLARE @CURR_MONTH_BEG AS DATE = DATEADD(DAY,1,EOMONTH(@CURR_MONTH_END,-1))

--ARCHIVE DATA2--
SELECT A.*
,PREV_MONTH_7_MCA,PREV_MONTH_7_STATUS,PREV_MONTH_7
,PREV_MONTH_8_MCA,PREV_MONTH_8_STATUS,PREV_MONTH_8
,PREV_MONTH_9_MCA,PREV_MONTH_9_STATUS,PREV_MONTH_9
,PREV_MONTH_10_MCA,PREV_MONTH_10_STATUS,PREV_MONTH_10
,PREV_MONTH_11_MCA,PREV_MONTH_11_STATUS,PREV_MONTH_11
,PREV_MONTH_12_MCA,PREV_MONTH_12_STATUS,PREV_MONTH_12
INTO #BASE2

FROM ##NTS_TS_EXCP1 A
LEFT JOIN (SELECT LOAN_NBR,MCA_PERCENT AS 'PREV_MONTH_7_MCA',LOAN_STATUS AS 'PREV_MONTH_7_STATUS',DATEADD(DAY,1,EOMONTH(@CURR_MONTH_END,-8)) AS 'PREV_MONTH_7' FROM tbl1 (DATEADD(DAY,1,EOMONTH(@CURR_MONTH_END,-8)),CAST(REPLACE(DATEADD(DAY,1,EOMONTH(@CURR_MONTH_END,-8)),'-','') AS INT))) I
	ON A.LOAN_NBR = I.LOAN_NBR
LEFT JOIN (SELECT LOAN_NBR,MCA_PERCENT AS 'PREV_MONTH_8_MCA',LOAN_STATUS AS 'PREV_MONTH_8_STATUS',DATEADD(DAY,1,EOMONTH(@CURR_MONTH_END,-9)) AS 'PREV_MONTH_8' FROM tbl1 (DATEADD(DAY,1,EOMONTH(@CURR_MONTH_END,-9)),CAST(REPLACE(DATEADD(DAY,1,EOMONTH(@CURR_MONTH_END,-9)),'-','') AS INT))) J
	ON A.LOAN_NBR = J.LOAN_NBR
LEFT JOIN (SELECT LOAN_NBR,MCA_PERCENT AS 'PREV_MONTH_9_MCA',LOAN_STATUS AS 'PREV_MONTH_9_STATUS',DATEADD(DAY,1,EOMONTH(@CURR_MONTH_END,-10)) AS 'PREV_MONTH_9' FROM tbl1 (DATEADD(DAY,1,EOMONTH(@CURR_MONTH_END,-10)),CAST(REPLACE(DATEADD(DAY,1,EOMONTH(@CURR_MONTH_END,-10)),'-','') AS INT))) K
	ON A.LOAN_NBR = K.LOAN_NBR
LEFT JOIN (SELECT LOAN_NBR,MCA_PERCENT AS 'PREV_MONTH_10_MCA',LOAN_STATUS AS 'PREV_MONTH_10_STATUS',DATEADD(DAY,1,EOMONTH(@CURR_MONTH_END,-11)) AS 'PREV_MONTH_10' FROM tbl1 (DATEADD(DAY,1,EOMONTH(@CURR_MONTH_END,-11)),CAST(REPLACE(DATEADD(DAY,1,EOMONTH(@CURR_MONTH_END,-11)),'-','') AS INT))) L
	ON A.LOAN_NBR = L.LOAN_NBR
LEFT JOIN (SELECT LOAN_NBR,MCA_PERCENT AS 'PREV_MONTH_11_MCA',LOAN_STATUS AS 'PREV_MONTH_11_STATUS',DATEADD(DAY,1,EOMONTH(@CURR_MONTH_END,-12)) AS 'PREV_MONTH_11' FROM tbl1 (DATEADD(DAY,1,EOMONTH(@CURR_MONTH_END,-12)),CAST(REPLACE(DATEADD(DAY,1,EOMONTH(@CURR_MONTH_END,-12)),'-','') AS INT))) M
	ON A.LOAN_NBR = M.LOAN_NBR
LEFT JOIN (SELECT LOAN_NBR,MCA_PERCENT AS 'PREV_MONTH_12_MCA',LOAN_STATUS AS 'PREV_MONTH_12_STATUS',DATEADD(DAY,1,EOMONTH(@CURR_MONTH_END,-13)) AS 'PREV_MONTH_12' FROM tbl1 (DATEADD(DAY,1,EOMONTH(@CURR_MONTH_END,-13)),CAST(REPLACE(DATEADD(DAY,1,EOMONTH(@CURR_MONTH_END,-13)),'-','') AS INT))) N
	ON A.LOAN_NBR = N.LOAN_NBR
	
