SET ANSI_WARNINGS OFF
SET NOCOUNT ON
SELECT A.LOAN_NBR,EXCP_COUNT,
CASE WHEN Claim_Filed IS NULL THEN CAST(DATE_SUBMIT_TO_HUD AS DATE) 
ELSE Claim_Filed
END AS 'Claim_Filed / Submitted to HUD'
,LOAN_STATUS,C.HUD_STS_DESC,EXCP_ID,DOC_DESC,EXCP_STS_DESC,TAG_2_VAL,INCRBL_FLG_DESC
INTO #BASE
FROM Reverse_DW.[dbo].[RM_CHAMPION_MASTER_TBL_CURR_VW] A
LEFT JOIN (SELECT LOAN_NBR,EXCP_ID,DOC_DESC,EXCP_STS_DESC FROM REVERSE_DW.[dbo].[HUD_ASGN_EXCP_EDW] WHERE CURR_IND ='Y' AND DOC_DESC <> 'FNMA Denied' AND EXCP_STS_DESC NOT IN ('Cancelled','RESOLVED','CLOSED','NOT VALID','CLOSED WITH VENDOR','Resolved by ML')) B
	ON CAST(A.LOAN_NBR AS VARCHAR) = CAST(B.LOAN_NBR AS VARCHAR)
LEFT JOIN (SELECT LOAN_NBR,HUD_STS_DESC FROM Reverse_dw.[dbo].[HUD_ASGN_HUD_STS] WHERE CURR_IND = 'Y' AND HUD_STS_DESC IN ('HUD Approval','HUD Approved','Pkg Submitted to HUD','Resubmitted to HUD','Rebuttal to HUD')) C
	ON CAST(A.LOAN_NBR AS VARCHAR) = CAST(C.LOAN_NBR AS VARCHAR)
LEFT JOIN (SELECT LOAN_NBR,TAG_2_VAL,INCRBL_FLG_DESC FROM REVERSE_DW.DBO.HUD_ASGN_LOANS WHERE CURR_IND = 'Y') D
	ON CAST(A.LOAN_NBR AS VARCHAR) = CAST(D.LOAN_NBR AS VARCHAR)
LEFT JOIN (SELECT LOAN_NBR,MAX([DT_SBMT_TO_HUD]) AS 'DATE_SUBMIT_TO_HUD'  FROM REVERSE_DW.[dbo].[HUD_ASSGN_DT_SBMT_RESBMT] GROUP BY LOAN_NBR) E
	ON CAST(A.LOAN_NBR AS VARCHAR) = CAST(E.LOAN_NBR AS VARCHAR)
LEFT JOIN (SELECT LOAN_NBR,COUNT(LOAN_NBR) AS 'EXCP_COUNT' FROM REVERSE_DW.[dbo].[HUD_ASGN_EXCP_EDW] WHERE CURR_IND ='Y' AND DOC_DESC <> 'FNMA Denied' AND EXCP_STS_DESC NOT IN ('Cancelled','RESOLVED','CLOSED','NOT VALID','CLOSED WITH VENDOR','Resolved by ML') GROUP BY LOAN_NBR) F
	ON CAST(A.LOAN_NBR AS VARCHAR) = CAST(F.LOAN_NBR AS VARCHAR)
LEFT JOIN (select loan_key, max([TXN_DT]) as 'Claim_Filed' from REVERSE_DW.[dbo].[LOAN_STS_EVT_TXN] where [OLD_LOAN_STS_CD] = '0' and [NEW_LOAN_STS_CD] = '72' group by loan_key) G
	ON CAST(A.loan_key AS VARCHAR) = CAST(G.loan_key As VARCHAR)
WHERE EXCP_ID IS NOT NULL AND (A.LOAN_STATUS LIKE '%Liquidated/Assigned to HU%' OR (C.HUD_STS_DESC IS NOT NULL AND LOAN_STATUS <> 'Inactive')) 

ORDER BY LOAN_STATUS,[Claim_Filed / Submitted to HUD] DESC

SELECT *,DATEPART(YEAR,[Claim_Filed / Submitted to HUD]) AS 'Year_Filed'  FROM #BASE

DROP TABLE #BASE
