DECLARE	@BOM DATE
DECLARE	@EOM DATE

DECLARE @BINT INT
DECLARE @EINT INT

SET @BOM = CAST('5/01/2020' AS DATE) --CAST(CAST(DATEPART(MONTH,GETDATE())-1 AS NVARCHAR) + CAST('/01/' AS NVARCHAR) + CAST(DATEPART(YEAR,GETDATE()) AS NVARCHAR) AS DATE) 
SET @EOM = CAST('5/31/2020' AS DATE)---CAST((SELECT MAX(BUS_PROC_DT) FROM tbl1 WHERE DATEPART(Month,BUS_PROC_DT) = DATEPART(M,GETDATE()) - 1) AS DATE)

SET @BINT = CAST(REPLACE(@BOM,'-','') AS INT)
SET @EINT = CAST(REPLACE(@EOM,'-','') AS INT)

SELECT * INTO #BASE FROM tbl2

--EXCP--
SELECT E.*,Open_Excp,Close_Excp,End_Excp 
INTO #EXCP 
FROM #BASE E 
LEFT JOIN (SELECT [EXCP_ID],MAX(Eff_DTTM) AS 'End_Excp' FROM #BASE WHERE (DOC_DESC IN ('Loss Draft') OR (ISSU_DESC IN ('Forced Placed Insurance')) OR (DOC_DESC = 'Not enough repay' AND ISSU_DESC = 'Call Center Action Req.')) AND CAST(Eff_DTTM AS DATE) <= CAST(@EOM AS DATE) GROUP BY EXCP_ID) D
	ON CAST(E.[EXCP_ID] AS NVARCHAR) = D.[EXCP_ID]
LEFT JOIN (SELECT [EXCP_ID],MAX(Eff_DTTM) AS 'Open_Excp' FROM #BASE WHERE (DOC_DESC IN ('Loss Draft') OR (ISSU_DESC IN ('Forced Placed Insurance')) OR (DOC_DESC = 'Not enough repay' AND ISSU_DESC = 'Call Center Action Req.')) AND Excp_Sts_Desc NOT IN ('RESOLVED','CLOSED','NOT VALID','CLOSED WITH VENDOR','INCURABLE') AND CAST(Eff_DTTM AS DATE) <= CAST(@EOM AS DATE) GROUP BY EXCP_ID) B
	ON CAST(E.[EXCP_ID] AS NVARCHAR) = B.[EXCP_ID]
LEFT JOIN (SELECT [EXCP_ID],MAX(Eff_DTTM) AS 'Close_Excp' FROM #BASE WHERE (DOC_DESC IN ('Loss Draft') OR (ISSU_DESC IN ('Forced Placed Insurance')) OR (DOC_DESC = 'Not enough repay' AND ISSU_DESC = 'Call Center Action Req.')) AND Excp_Sts_Desc IN ('RESOLVED','CLOSED','NOT VALID','CLOSED WITH VENDOR','INCURABLE') AND CAST(Eff_DTTM AS DATE) BETWEEN CAST(@BOM AS DATE) AND CAST(@EOM AS DATE) GROUP BY EXCP_ID) C
	ON E.[EXCP_ID] = C.[EXCP_ID]
WHERE CAST(Eff_DTTM AS DATE) <= CAST(@EOM AS DATE)  AND (DOC_DESC IN ('Loss Draft') OR ((ISSU_DESC IN ('Forced Placed Insurance')) OR (DOC_DESC = 'Not enough repay' AND ISSU_DESC = 'Call Center Action Req.')))

--BOM MCA--
SELECT A.LOAN_NBR,A.MCA_PERCENT AS 'BOM_MCA',A.LOAN_STATUS AS 'BOM_LOAN_STATUS'
INTO #BOM_MCA
FROM tbl3 (@BOM,@BINT) A 
RIGHT JOIN #EXCP EXCP
ON A.Loan_Nbr = EXCP.Loan_Nbr


--FINAL--
SELECT DISTINCT A.Loan_Nbr,BOM_MCA,A.MCA_PERCENT AS 'EOM_MCA',CASE WHEN BOM_MCA >= 97.5 THEN '>=97.5' ELSE '<97.5'END AS 'BOM_MCA_FLAG',[BOM_LOAN_STATUS],A.LOAN_STATUS AS 'EOM_LOAN_STATUS',EXCP.EXCP_ID,CAST(@BOM AS DATE) AS 'Month',ISNULL(EXCP.DOC_DESC,'No Exception') AS 'Doc_Desc',EXCP.ISSU_DESC,EXCP.[EXCP_STS_DESC]
,CASE WHEN Excp.[EXCP_STS_DESC] IN ('Resolved','Not Valid') THEN 'Exception Closed'
	  WHEN BOM_LOAN_STATUS = 'ACTIVE' AND A.LOAN_STATUS <> 'ACTIVE' THEN 'LOAN RESOLVED - DEFAULT or LIQ' 
	  WHEN ISNULL(Excp.[EXCP_STS_DESC],'In Process') IN ('In Process','Clarity Required','New Exception','Clarity Provided','Cured in Error') THEN 'Exception Open'
	  WHEN Excp.EXCP_STS_DESC IS NULL THEN 'No Exception'
	  END AS 'Exception Status'
,EXCP.EFF_DTTM,ISNULL(Open_Excp,EXCP.[EXCP_RQST_DTTM]) AS 'Open_Excp',Close_Excp
FROM  tbl3 (@EOM,@EINT) A--tbl4 A
/*LEFT JOIN (SELECT * FROM tbl2  WHERE (DOC_DESC IN ('Loss Draft') OR ISSU_DESC IN ('Forced Placed Insurance','Not enough repays')) AND CAST(Eff_DTTM AS DATE) <= CAST(@EOM AS DATE)) E
	ON A.Loan_Nbr = E.LOAN_NBR
LEFT JOIN (SELECT [EXCP_ID],MAX(Eff_DTTM) AS 'End_Excp' FROM tbl2 WHERE (DOC_DESC IN ('Loss Draft') OR (ISSU_DESC IN ('Forced Placed Insurance')) OR (DOC_DESC = 'Not enough repays' AND ISSU_DESC = 'Call Center Action Required')) AND CAST(Eff_DTTM AS DATE) <= CAST(@EOM AS DATE) GROUP BY EXCP_ID) D
	ON CAST(E.[EXCP_ID] AS NVARCHAR) = D.[EXCP_ID]
LEFT JOIN (SELECT [EXCP_ID],MAX(Eff_DTTM) AS 'Open_Excp' FROM tbl2 WHERE (DOC_DESC IN ('Loss Draft') OR (ISSU_DESC IN ('Forced Placed Insurance')) OR (DOC_DESC = 'Not enough repays' AND ISSU_DESC = 'Call Center Action Required')) AND Excp_Sts_Desc NOT IN ('RESOLVED','CLOSED','NOT VALID','CLOSED WITH VENDOR','INCURABLE') AND CAST(Eff_DTTM AS DATE) <= CAST(@EOM AS DATE) GROUP BY EXCP_ID) B
	ON CAST(E.[EXCP_ID] AS NVARCHAR) = B.[EXCP_ID]
LEFT JOIN (SELECT [EXCP_ID],MAX(Eff_DTTM) AS 'Close_Excp' FROM tbl2 WHERE (DOC_DESC IN ('Loss Draft') OR (ISSU_DESC IN ('Forced Placed Insurance')) OR (DOC_DESC = 'Not enough repays' AND ISSU_DESC = 'Call Center Action Required')) AND Excp_Sts_Desc IN ('RESOLVED','CLOSED','NOT VALID','CLOSED WITH VENDOR','INCURABLE') AND CAST(Eff_DTTM AS DATE) BETWEEN CAST(@BOM AS DATE) AND CAST(@EOM AS DATE) GROUP BY EXCP_ID) C
	ON E.[EXCP_ID] = C.[EXCP_ID]*/

RIGHT JOIN #EXCP EXCP
	ON A.Loan_Nbr = EXCP.Loan_Nbr
LEFT JOIN #BOM_MCA BOM
ON BOM.Loan_Nbr = EXCP.Loan_Nbr

WHERE (EXCP.EFF_DTTM = End_Excp) AND ((Close_Excp BETWEEN @BOM AND @EOM) OR (Close_Excp IS NULL AND EXCP.Excp_Sts_Desc NOT IN ('RESOLVED','CLOSED','NOT VALID','CLOSED WITH VENDOR','INCURABLE')))

DROP TABLE #EXCP,#BOM_MCA,#BASE

